// MARK: - PostKit
// GeneratedPost.swift — GeneratedPost SwiftData model and related types

import Foundation
import SwiftData

enum SocialPlatform: String, Codable, CaseIterable, Sendable {
    case instagram, tiktok, twitter, linkedin, reddit, pinterest

    var displayName: String {
        switch self {
        case .twitter: "X"
        default: rawValue.capitalized
        }
    }

    var icon: String {
        switch self {
        case .instagram: "camera.fill"
        case .tiktok: "play.rectangle.fill"
        case .twitter: "at"
        case .linkedin: "briefcase.fill"
        case .reddit: "bubble.left.fill"
        case .pinterest: "pin.fill"
        }
    }

    var characterLimit: Int {
        switch self {
        case .instagram: 2200
        case .tiktok: 2200
        case .twitter: 280
        case .linkedin: 3000
        case .reddit: 40000
        case .pinterest: 500
        }
    }
}

enum PostStatus: String, Codable, CaseIterable, Sendable {
    case draft, ready, published
}

@Model
final class GeneratedPost {
    var id: UUID
    var title: String = ""
    var pillarID: UUID
    var templateID: UUID?
    var photoIDsData: Data?
    var caption: String = ""
    var hashtagsData: Data?
    var platformRaw: String = SocialPlatform.instagram.rawValue
    var statusRaw: String = PostStatus.draft.rawValue
    var isAutoGenerated: Bool = false
    var createdAt: Date

    var photoIDs: [String] {
        get {
            guard let data = photoIDsData else { return [] }
            return (try? JSONDecoder().decode([String].self, from: data)) ?? []
        }
        set {
            photoIDsData = try? JSONEncoder().encode(newValue)
        }
    }

    var hashtags: [String] {
        get {
            guard let data = hashtagsData else { return [] }
            return (try? JSONDecoder().decode([String].self, from: data)) ?? []
        }
        set {
            hashtagsData = try? JSONEncoder().encode(newValue)
        }
    }

    var platform: SocialPlatform {
        get { SocialPlatform(rawValue: platformRaw) ?? .instagram }
        set { platformRaw = newValue.rawValue }
    }

    var status: PostStatus {
        get { PostStatus(rawValue: statusRaw) ?? .draft }
        set { statusRaw = newValue.rawValue }
    }

    init(
        title: String = "",
        pillarID: UUID,
        templateID: UUID? = nil,
        photoIDs: [String] = [],
        caption: String = "",
        hashtags: [String] = [],
        platform: SocialPlatform = .instagram,
        status: PostStatus = .draft,
        isAutoGenerated: Bool = false,
        createdAt: Date = .now
    ) {
        self.id = UUID()
        self.title = title
        self.pillarID = pillarID
        self.templateID = templateID
        self.photoIDsData = try? JSONEncoder().encode(photoIDs)
        self.caption = caption
        self.hashtagsData = try? JSONEncoder().encode(hashtags)
        self.platformRaw = platform.rawValue
        self.statusRaw = status.rawValue
        self.isAutoGenerated = isAutoGenerated
        self.createdAt = createdAt
    }
}
