// MARK: - PostKit
// Snapshots.swift — Value-type snapshots for pillars, photos, posts, and templates

import Foundation

struct PillarSnapshot: Equatable, Identifiable, Sendable {
    let id: UUID
    var name: String
    var emoji: String
    var about: String
    var tone: PillarTone
    var topics: [String]
    var referenceTags: [String]
    var referencePhotoIDs: [String]
    var photoCount: Int
    var postsPerWeek: Int
    var colorHex: String
    var topPhotoAssetIDs: [String]

    init(
        id: UUID = UUID(),
        name: String,
        emoji: String,
        about: String = "",
        tone: PillarTone = .casual,
        topics: [String] = [],
        referenceTags: [String] = [],
        referencePhotoIDs: [String] = [],
        colorHex: String = "#8b5cf6",
        photoCount: Int = 0,
        postsPerWeek: Int = 3,
        topPhotoAssetIDs: [String] = []
    ) {
        self.id = id
        self.name = name
        self.emoji = emoji
        self.about = about
        self.tone = tone
        self.topics = topics
        self.referenceTags = referenceTags
        self.referencePhotoIDs = referencePhotoIDs
        self.colorHex = colorHex
        self.photoCount = photoCount
        self.postsPerWeek = postsPerWeek
        self.topPhotoAssetIDs = topPhotoAssetIDs
    }

    init(_ pillar: Pillar, photoCount: Int = 0) {
        self.id = pillar.id
        self.name = pillar.name
        self.emoji = pillar.emoji
        self.about = pillar.about
        self.tone = pillar.tone
        self.topics = pillar.topics
        self.referenceTags = pillar.referenceTags
        self.referencePhotoIDs = pillar.referencePhotoIDs
        self.photoCount = photoCount
        self.postsPerWeek = pillar.postsPerWeek
        self.colorHex = pillar.colorHex
        self.topPhotoAssetIDs = []
    }
}

struct ClassifiedPhotoSnapshot: Equatable, Identifiable, Sendable {
    let id: UUID
    var assetLocalIdentifier: String
    var pillarID: UUID?
    var pillarIDs: [UUID]
    var confidence: Float
    var classifiedByAI: Bool
    var tags: [String]
    var location: String?
    var latitude: Double?
    var longitude: Double?
    var capturedAt: Date?
    var status: ClassifiedPhoto.PhotoStatus
    var cadrage: Cadrage?

    init(
        id: UUID = UUID(),
        assetLocalIdentifier: String,
        pillarID: UUID? = nil,
        pillarIDs: [UUID] = [],
        confidence: Float = 0,
        classifiedByAI: Bool = true,
        tags: [String] = [],
        location: String? = nil,
        latitude: Double? = nil,
        longitude: Double? = nil,
        capturedAt: Date? = nil,
        status: ClassifiedPhoto.PhotoStatus = .pending,
        cadrage: Cadrage? = nil
    ) {
        self.id = id
        self.assetLocalIdentifier = assetLocalIdentifier
        self.pillarID = pillarID
        self.pillarIDs = pillarIDs
        self.confidence = confidence
        self.classifiedByAI = classifiedByAI
        self.tags = tags
        self.location = location
        self.latitude = latitude
        self.longitude = longitude
        self.capturedAt = capturedAt
        self.status = status
        self.cadrage = cadrage
    }

    init(_ photo: ClassifiedPhoto) {
        self.id = photo.id
        self.assetLocalIdentifier = photo.assetLocalIdentifier
        self.pillarID = photo.pillarID
        self.pillarIDs = photo.pillarIDs
        self.confidence = photo.confidence
        self.classifiedByAI = photo.classifiedByAI
        self.tags = photo.tags
        self.location = photo.location
        self.latitude = photo.latitude
        self.longitude = photo.longitude
        self.capturedAt = photo.capturedAt
        self.status = photo.status
        self.cadrage = photo.cadrage
    }
}

struct GeneratedPostSnapshot: Equatable, Identifiable, Sendable {
    let id: UUID
    var title: String
    var pillarID: UUID
    var templateID: UUID?
    var photoIDs: [String]
    var caption: String
    var hashtags: [String]
    var platform: SocialPlatform
    var status: PostStatus
    var isAutoGenerated: Bool
    var schedule: TemplateSchedule
    var createdAt: Date

    init(
        id: UUID = UUID(),
        title: String = "",
        pillarID: UUID,
        templateID: UUID? = nil,
        photoIDs: [String] = [],
        caption: String = "",
        hashtags: [String] = [],
        platform: SocialPlatform = .instagram,
        status: PostStatus = .draft,
        isAutoGenerated: Bool = false,
        schedule: TemplateSchedule = TemplateSchedule(),
        createdAt: Date = .now
    ) {
        self.id = id
        self.title = title
        self.pillarID = pillarID
        self.templateID = templateID
        self.photoIDs = photoIDs
        self.caption = caption
        self.hashtags = hashtags
        self.platform = platform
        self.status = status
        self.isAutoGenerated = isAutoGenerated
        self.schedule = schedule
        self.createdAt = createdAt
    }

    init(_ post: GeneratedPost) {
        self.id = post.id
        self.title = post.title
        self.pillarID = post.pillarID
        self.templateID = post.templateID
        self.photoIDs = post.photoIDs
        self.caption = post.caption
        self.hashtags = post.hashtags
        self.platform = post.platform
        self.status = post.status
        self.isAutoGenerated = post.isAutoGenerated
        self.schedule = post.schedule
        self.createdAt = post.createdAt
    }
}

struct TemplateSnapshot: Equatable, Identifiable, Sendable {
    let id: UUID
    var name: String
    var about: String
    var slots: [TemplateSlotData]
    var locations: [String]
    var schedule: TemplateSchedule
    var lastPostedAt: Date?
    var createdAt: Date

    init(
        id: UUID = UUID(),
        name: String,
        about: String = "",
        slots: [TemplateSlotData] = [],
        locations: [String] = [],
        schedule: TemplateSchedule = TemplateSchedule(),
        lastPostedAt: Date? = nil,
        createdAt: Date = .now
    ) {
        self.id = id
        self.name = name
        self.about = about
        self.slots = slots
        self.locations = locations
        self.schedule = schedule
        self.lastPostedAt = lastPostedAt
        self.createdAt = createdAt
    }

    init(_ template: PostTemplate) {
        self.id = template.id
        self.name = template.name
        self.about = template.about
        self.slots = template.slots
        self.locations = template.locations
        self.schedule = template.schedule
        self.lastPostedAt = template.lastPostedAt
        self.createdAt = template.createdAt
    }
}
